service: naporta-api

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1
  memorySize: 512
  timeout: 15

functions:
  api:
    handler: dist/lambda.handler
    events:
      - httpApi:
          path: /{proxy+}
          method: '*'

plugins:
  - serverless-offline